# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ilkdeneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1853, 1042)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QWidget {\n"
"    background-color: #D6EFD8;  /* Krem rengi arka plan */\n"
"    background-image: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 1,\n"
"        stop: 0 #FFF8E1, stop: 1 #FFE082\n"
"    );  /* Krem rengi gradyan efekti */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    border: 1px solid #508D4E;  /* Canlı yeşil kenarlık */\n"
"    border-radius: 15px;  /* Yuvarlatılmış köşeler */\n"
"}\n"
"\n"
"QLabel, QSlider, QLineEdit, QPushButton {\n"
"    color: #212121;  /* Koyu gri yazı rengi */\n"
"    background-color: #4CAF50;  /* Canlı yeşil arka plan */\n"
"    border: 1px solid #C8E6C9;  /* Açık yeşil kenarlık */\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);  /* Hafif siyah gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C8E6C9;  /* Hover durumunda açık yeşil */\n"
"    border: 1px solid #4CAF50;  /* Canlı yeşil kenarlık */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);  /* Hover\'da daha belirgin siyah gölge */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #F1F8E9;  /* Çok açık yeşil arka plan */\n"
"    border: 1px solid #4CAF50;  /* Canlı yeşil kenarlık */\n"
"    padding: 5px;\n"
"    color: #212121;  /* Koyu gri yazı rengi */\n"
"}\n"
"")
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.anasayfa = QtWidgets.QWidget()
        self.anasayfa.setObjectName("anasayfa")
        self.stackedWidget = QtWidgets.QStackedWidget(self.anasayfa)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 1141, 891))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page)
        self.groupBox_4.setGeometry(QtCore.QRect(630, 30, 471, 281))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("font: 63 9pt \"Cascadia Code SemiBold\";")
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_x_plus = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_x_plus.setGeometry(QtCore.QRect(40, 30, 91, 51))
        self.pushButton_x_plus.setStyleSheet("")
        self.pushButton_x_plus.setObjectName("pushButton_x_plus")
        self.pushButton_x_minus = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_x_minus.setGeometry(QtCore.QRect(40, 100, 91, 51))
        self.pushButton_x_minus.setStyleSheet("")
        self.pushButton_x_minus.setObjectName("pushButton_x_minus")
        self.pushButton_y_plus = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_y_plus.setGeometry(QtCore.QRect(190, 30, 91, 51))
        self.pushButton_y_plus.setStyleSheet("")
        self.pushButton_y_plus.setObjectName("pushButton_y_plus")
        self.pushButton_y_minus = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_y_minus.setGeometry(QtCore.QRect(190, 100, 91, 51))
        self.pushButton_y_minus.setStyleSheet("")
        self.pushButton_y_minus.setObjectName("pushButton_y_minus")
        self.pushButton_z_plus = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_z_plus.setGeometry(QtCore.QRect(330, 30, 91, 51))
        self.pushButton_z_plus.setStyleSheet("")
        self.pushButton_z_plus.setObjectName("pushButton_z_plus")
        self.pushButton_z_minus = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_z_minus.setGeometry(QtCore.QRect(330, 100, 91, 51))
        self.pushButton_z_minus.setStyleSheet("")
        self.pushButton_z_minus.setObjectName("pushButton_z_minus")
        self.comboBox_carpan_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_carpan_2.setGeometry(QtCore.QRect(310, 180, 111, 31))
        self.comboBox_carpan_2.setStyleSheet("QWidget {\n"
"    background-color: #E8F5E9;  /* Açık yeşil arka plan */\n"
"    background-image: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 1,\n"
"        stop: 0 #E8F5E9, stop: 1 #C8E6C9\n"
"    );  /* Açık yeşil gradyan efekti */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    border: 1px solid #4CAF50;  /* Canlı yeşil kenarlık */\n"
"    border-radius: 15px;  /* Yuvarlatılmış köşeler */\n"
"}\n"
"\n"
"QLabel, QSlider, QLineEdit, QPushButton {\n"
"    color: #212121;  /* Koyu gri yazı rengi */\n"
"    background-color: #4CAF50;  /* Canlı yeşil arka plan */\n"
"    border: 1px solid #C8E6C9;  /* Açık yeşil kenarlık */\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);  /* Hafif siyah gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #C8E6C9;  /* Hover durumunda açık yeşil */\n"
"    border: 1px solid #4CAF50;  /* Canlı yeşil kenarlık */\n"
"    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3);  /* Hover\'da daha belirgin siyah gölge */\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #F1F8E9;  /* Çok açık yeşil arka plan */\n"
"    border: 1px solid #4CAF50;  /* Canlı yeşil kenarlık */\n"
"    padding: 5px;\n"
"    color: #212121;  /* Koyu gri yazı rengi */\n"
"}\n"
"\n"
"    ")
        self.comboBox_carpan_2.setCurrentText("")
        self.comboBox_carpan_2.setObjectName("comboBox_carpan_2")
        self.comboBox_carpan_2.addItem("")
        self.comboBox_carpan_2.addItem("")
        self.comboBox_carpan_2.addItem("")
        self.comboBox_carpan_2.addItem("")
        self.comboBox_carpan_2.addItem("")
        self.comboBox_carpan_2.addItem("")
        self.comboBox_carpan_2.addItem("")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(40, 180, 221, 31))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 571, 281))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_eklem1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_eklem1.setGeometry(QtCore.QRect(340, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_eklem1.setFont(font)
        self.label_eklem1.setObjectName("label_eklem1")
        self.label_eklem2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_eklem2.setGeometry(QtCore.QRect(340, 70, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_eklem2.setFont(font)
        self.label_eklem2.setObjectName("label_eklem2")
        self.label_eklem3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_eklem3.setGeometry(QtCore.QRect(340, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_eklem3.setFont(font)
        self.label_eklem3.setObjectName("label_eklem3")
        self.label_eklem4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_eklem4.setGeometry(QtCore.QRect(340, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_eklem4.setFont(font)
        self.label_eklem4.setObjectName("label_eklem4")
        self.label_eklem5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_eklem5.setGeometry(QtCore.QRect(340, 190, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_eklem5.setFont(font)
        self.label_eklem5.setObjectName("label_eklem5")
        self.label_eklem6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_eklem6.setGeometry(QtCore.QRect(340, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_eklem6.setFont(font)
        self.label_eklem6.setObjectName("label_eklem6")
        self.slider_joint1 = QtWidgets.QSlider(self.groupBox_2)
        self.slider_joint1.setGeometry(QtCore.QRect(10, 25, 160, 21))
        self.slider_joint1.setMinimum(-140)
        self.slider_joint1.setMaximum(140)
        self.slider_joint1.setProperty("value", 0)
        self.slider_joint1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint1.setInvertedAppearance(False)
        self.slider_joint1.setInvertedControls(False)
        self.slider_joint1.setObjectName("slider_joint1")
        self.slider_joint2 = QtWidgets.QSlider(self.groupBox_2)
        self.slider_joint2.setGeometry(QtCore.QRect(10, 65, 160, 22))
        self.slider_joint2.setMinimum(-60)
        self.slider_joint2.setMaximum(130)
        self.slider_joint2.setProperty("value", 0)
        self.slider_joint2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint2.setObjectName("slider_joint2")
        self.slider_joint3 = QtWidgets.QSlider(self.groupBox_2)
        self.slider_joint3.setGeometry(QtCore.QRect(10, 110, 160, 22))
        self.slider_joint3.setMinimum(-135)
        self.slider_joint3.setMaximum(70)
        self.slider_joint3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint3.setObjectName("slider_joint3")
        self.slider_joint4 = QtWidgets.QSlider(self.groupBox_2)
        self.slider_joint4.setGeometry(QtCore.QRect(10, 155, 160, 21))
        self.slider_joint4.setMinimum(-180)
        self.slider_joint4.setMaximum(180)
        self.slider_joint4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint4.setObjectName("slider_joint4")
        self.slider_joint5 = QtWidgets.QSlider(self.groupBox_2)
        self.slider_joint5.setGeometry(QtCore.QRect(10, 200, 160, 22))
        self.slider_joint5.setMinimum(-45)
        self.slider_joint5.setMaximum(90)
        self.slider_joint5.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint5.setObjectName("slider_joint5")
        self.slider_joint6 = QtWidgets.QSlider(self.groupBox_2)
        self.slider_joint6.setGeometry(QtCore.QRect(10, 245, 160, 22))
        self.slider_joint6.setMinimum(-180)
        self.slider_joint6.setMaximum(180)
        self.slider_joint6.setOrientation(QtCore.Qt.Horizontal)
        self.slider_joint6.setObjectName("slider_joint6")
        self.textbox_joint1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_joint1.setGeometry(QtCore.QRect(200, 20, 111, 31))
        self.textbox_joint1.setDragEnabled(False)
        self.textbox_joint1.setObjectName("textbox_joint1")
        self.textbox_joint2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_joint2.setGeometry(QtCore.QRect(200, 60, 111, 31))
        self.textbox_joint2.setDragEnabled(False)
        self.textbox_joint2.setObjectName("textbox_joint2")
        self.textbox_joint3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_joint3.setGeometry(QtCore.QRect(200, 105, 111, 31))
        self.textbox_joint3.setObjectName("textbox_joint3")
        self.textbox_joint4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_joint4.setGeometry(QtCore.QRect(200, 150, 111, 31))
        self.textbox_joint4.setObjectName("textbox_joint4")
        self.textbox_joint5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_joint5.setGeometry(QtCore.QRect(200, 195, 111, 31))
        self.textbox_joint5.setObjectName("textbox_joint5")
        self.textbox_joint6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_joint6.setGeometry(QtCore.QRect(200, 240, 111, 31))
        self.textbox_joint6.setObjectName("textbox_joint6")
        self.pushButton_ilerle = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_ilerle.setGeometry(QtCore.QRect(452, 110, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        self.pushButton_ilerle.setFont(font)
        self.pushButton_ilerle.setObjectName("pushButton_ilerle")
        self.widget_graphic = QtWidgets.QWidget(self.page)
        self.widget_graphic.setGeometry(QtCore.QRect(30, 320, 571, 441))
        self.widget_graphic.setObjectName("widget_graphic")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page)
        self.groupBox_3.setGeometry(QtCore.QRect(640, 670, 461, 151))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_gripperonoff = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_gripperonoff.setGeometry(QtCore.QRect(140, 30, 181, 101))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_gripperonoff.setFont(font)
        self.pushButton_gripperonoff.setStyleSheet("")
        self.pushButton_gripperonoff.setCheckable(False)
        self.pushButton_gripperonoff.setChecked(False)
        self.pushButton_gripperonoff.setObjectName("pushButton_gripperonoff")
        self.label_position = QtWidgets.QLabel(self.page)
        self.label_position.setGeometry(QtCore.QRect(210, 770, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_position.setFont(font)
        self.label_position.setText("")
        self.label_position.setObjectName("label_position")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(640, 400, 461, 181))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 31, 30))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setScaledContents(False)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(20, 80, 31, 29))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setScaledContents(False)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(20, 130, 31, 29))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setScaledContents(False)
        self.label_18.setObjectName("label_18")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(70, 30, 161, 30))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 80, 161, 29))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(70, 130, 161, 29))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_koordinat = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_koordinat.setGeometry(QtCore.QRect(300, 70, 111, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_koordinat.setFont(font)
        self.pushButton_koordinat.setObjectName("pushButton_koordinat")
        self.stackedWidget.addWidget(self.page)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.anasayfa)
        self.stackedWidget_2.setGeometry(QtCore.QRect(1170, 20, 631, 561))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_kameraac = QtWidgets.QPushButton(self.page_2)
        self.pushButton_kameraac.setGeometry(QtCore.QRect(120, 460, 111, 71))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_kameraac.setFont(font)
        self.pushButton_kameraac.setStyleSheet("")
        self.pushButton_kameraac.setObjectName("pushButton_kameraac")
        self.pushButton_kamerakapat = QtWidgets.QPushButton(self.page_2)
        self.pushButton_kamerakapat.setGeometry(QtCore.QRect(420, 460, 111, 71))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_kamerakapat.setFont(font)
        self.pushButton_kamerakapat.setStyleSheet("")
        self.pushButton_kamerakapat.setObjectName("pushButton_kamerakapat")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(30, 50, 571, 381))
        self.label_14.setFrameShape(QtWidgets.QFrame.Box)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_14.setLineWidth(5)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.stackedWidget_2.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_2.addWidget(self.page_3)
        self.label_2 = QtWidgets.QLabel(self.anasayfa)
        self.label_2.setGeometry(QtCore.QRect(1170, 770, 191, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("kourobotics_logo2.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.anasayfa)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(1370, 770, 431, 131))
        self.textEdit.setObjectName("textEdit")
        self.groupBox_6 = QtWidgets.QGroupBox(self.anasayfa)
        self.groupBox_6.setGeometry(QtCore.QRect(1180, 610, 621, 131))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(9)
        font.setBold(True)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_foto = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_foto.setGeometry(QtCore.QRect(170, 30, 121, 71))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_foto.setFont(font)
        self.pushButton_foto.setObjectName("pushButton_foto")
        self.pushButton_baslangic = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_baslangic.setGeometry(QtCore.QRect(20, 30, 121, 71))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_baslangic.setFont(font)
        self.pushButton_baslangic.setObjectName("pushButton_baslangic")
        self.pushButton_yaklas = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_yaklas.setGeometry(QtCore.QRect(320, 30, 121, 71))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_yaklas.setFont(font)
        self.pushButton_yaklas.setObjectName("pushButton_yaklas")
        self.pushButton_sepet = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_sepet.setGeometry(QtCore.QRect(480, 30, 121, 71))
        font = QtGui.QFont()
        font.setBold(True)
        self.pushButton_sepet.setFont(font)
        self.pushButton_sepet.setObjectName("pushButton_sepet")
        self.tabWidget.addTab(self.anasayfa, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1853, 22))
        self.menubar.setObjectName("menubar")
        self.menuKontrol = QtWidgets.QMenu(self.menubar)
        self.menuKontrol.setObjectName("menuKontrol")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuKontrol.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_carpan_2.setCurrentIndex(-1)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>h</p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Koordinat Kontrol Tuşları"))
        self.pushButton_x_plus.setText(_translate("MainWindow", "X+"))
        self.pushButton_x_minus.setText(_translate("MainWindow", "X-"))
        self.pushButton_y_plus.setText(_translate("MainWindow", "Y+"))
        self.pushButton_y_minus.setText(_translate("MainWindow", "Y-"))
        self.pushButton_z_plus.setText(_translate("MainWindow", "Z+"))
        self.pushButton_z_minus.setText(_translate("MainWindow", "Z-"))
        self.comboBox_carpan_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_carpan_2.setItemText(1, _translate("MainWindow", "3"))
        self.comboBox_carpan_2.setItemText(2, _translate("MainWindow", "5"))
        self.comboBox_carpan_2.setItemText(3, _translate("MainWindow", "10"))
        self.comboBox_carpan_2.setItemText(4, _translate("MainWindow", "20"))
        self.comboBox_carpan_2.setItemText(5, _translate("MainWindow", "50"))
        self.comboBox_carpan_2.setItemText(6, _translate("MainWindow", "100"))
        self.label.setText(_translate("MainWindow", "Koordinat Çarpanı (mm)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Slider"))
        self.label_eklem1.setText(_translate("MainWindow", "1.EKLEM "))
        self.label_eklem2.setText(_translate("MainWindow", "2.EKLEM"))
        self.label_eklem3.setText(_translate("MainWindow", "3.EKLEM"))
        self.label_eklem4.setText(_translate("MainWindow", "4.EKLEM"))
        self.label_eklem5.setText(_translate("MainWindow", "5.EKLEM"))
        self.label_eklem6.setText(_translate("MainWindow", "UÇ İŞLEVCİ"))
        self.pushButton_ilerle.setText(_translate("MainWindow", "İLERLE"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gripper Kontrol Tuşları"))
        self.pushButton_gripperonoff.setText(_translate("MainWindow", "Gripper Aç / Kapat"))
        self.groupBox.setTitle(_translate("MainWindow", "Koordinat Giriniz"))
        self.label_16.setText(_translate("MainWindow", "X     :"))
        self.label_17.setText(_translate("MainWindow", "Y     :"))
        self.label_18.setText(_translate("MainWindow", "Z     :"))
        self.pushButton_koordinat.setText(_translate("MainWindow", "GİT"))
        self.pushButton_kameraac.setText(_translate("MainWindow", "Kamera Aç"))
        self.pushButton_kamerakapat.setText(_translate("MainWindow", "Kamera Kapat"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">KILAVUZ KOU Robotics </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">GRAP </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">- Greenhouse Robot for Automated Picking -</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:600;\">- 2024 -</span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Konumlar"))
        self.pushButton_foto.setText(_translate("MainWindow", "Fotoğraf"))
        self.pushButton_baslangic.setText(_translate("MainWindow", "Başlangıç"))
        self.pushButton_yaklas.setText(_translate("MainWindow", "Yaklaş"))
        self.pushButton_sepet.setText(_translate("MainWindow", "Sepet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.anasayfa), _translate("MainWindow", "Robot Kinematik Analizi"))
        self.menuKontrol.setTitle(_translate("MainWindow", "Kontrol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
